# Generated by Django 5.2.8 on 2026-07-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_tag', models.CharField(choices=[('all', 'Unisex / All'), ('girl', 'Girl'), ('boy', 'Boy')], default='all', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('image_thumb_back', models.URLField(blank=True, null=True)),
                ('image_zoom_detail', models.URLField(blank=True, null=True)),
                ('brand', models.CharField(default='BabyBloom Atelier', max_length=100)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('age_group', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=10)),
                ('product_tags', models.CharField(default='Organic, New Arrival', max_length=250)),
                ('active_offer_percentage', models.PositiveIntegerField(default=0)),
                ('card_extra_discount_percentage', models.PositiveIntegerField(default=5)),
                ('upi_cashback_reward', models.FloatField(default=50.0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_admin_approved', models.BooleanField(default=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory')),
            ],
        ),
    ]
