# Generated by Django 5.2.8 on 2026-07-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_thumb_back',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_zoom_detail',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste direct web images here', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.FloatField(default=0.0, help_text='The regular retail store price (M.R.P.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='Fallback system path link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='The active customer selling price (Offer Price)'),
        ),
    ]
