# Generated by Django 5.2.8 on 2026-07-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_active_offer_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_partner',
            field=models.CharField(default='Bluedart Premium Nursery Delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.CharField(default='Within 3-5 Working Days', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_bonus_savings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_selected',
            field=models.CharField(default='Unselected', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='card_extra_discount_percentage',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='image_thumb_back',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_zoom_detail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=models.CharField(default='Organic, New Arrival, Baby Safe', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='upi_cashback_reward',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Processing', 'Processing Layout'), ('Shipped', 'Handed over to Courier'), ('Delivered', 'Delivered Safely'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
