# Generated by Django 5.2.8 on 2026-07-03 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_courier_partner_order_estimated_delivery_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='submitted_by',
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_partner',
            field=models.CharField(default='Bluedart Premium Logistics', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.CharField(default='3-5 Business Days', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Processing', 'Processing'), ('Shipped', 'Shipped via Courier'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method_selected',
            field=models.CharField(default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='BabyBloom Atelier', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender_tag',
            field=models.CharField(choices=[('all', 'Unisex / All'), ('girl', 'Girl'), ('boy', 'Boy')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.CharField(default='Organic, New Arrival', max_length=250),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
